### ISSUE TITLE
Get rid of the non-stuvus code and get this repo reviewed!

### ISSUE THREAD

**Issue by dasJ** [stuvusIT/iscsi-target#2]
![](https://media.giphy.com/media/5xaOcLLtd80AWPkP3xK/giphy.gif)

**Comment by SlothOfAnarchy** [comment]
when #1 is merged there is basically no non-stuvus code left.

**Comment by dasJ** [comment]
What about the reviews?

**Comment by SlothOfAnarchy** [comment]
review #1 then you have your review.

**Comment by dasJ** [comment]
How can I be sure everything is changed in the PR? And if it is, why fork a repo in the first place?

**Comment by SlothOfAnarchy** [comment]
I said basically, but I can remove all files and recommit them, if you want this reviewed so badly.
I like to attribute the work that went into this, that's why I forked it.
